plugins {
    id 'net.fabricmc.fabric-loom-remap' version "${loom_version}"
    id 'com.diffplug.spotless' version "${spotless_version}"
    id 'checkstyle'
    id 'maven-publish'
    id 'me.modmuss50.mod-publish-plugin' version "${mod_publish_plugin_version}"
}

version = "${mod_version}+${minecraft_version}"
group = maven_group

base {
    archivesName = archives_base_name
}

repositories {
    mavenCentral()

    // Fabric / Terraformers
    exclusiveContent {
        forRepository {
            maven {
                url = 'https://maven.terraformersmc.com/releases'
            }
        }
        filter {
            includeGroup 'com.terraformersmc'
        }
    }

    // SpongePowered
    maven {
        url = 'https://repo.spongepowered.org/repository/maven-public/'
    }
}

dependencies {
    minecraft "com.mojang:minecraft:${minecraft_version}"
	mappings loom.officialMojangMappings()

    implementation "net.fabricmc:fabric-loader:${loader_version}"
    implementation "net.fabricmc.fabric-api:fabric-api:${fabric_api_version}"

    // JSON Serialization & Annotations
    implementation "com.google.code.gson:gson:${gson_version}"
    compileOnly "org.checkerframework:checker-qual:${checker_qual_version}"

    // Testing
    testImplementation "net.fabricmc:fabric-loader-junit:${loader_version}"
    testImplementation 'org.junit.jupiter:junit-jupiter-api:5.10.2'
    testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine:5.10.2'
}

loom {
    accessWidenerPath = file('src/main/resources/moulconfig.accesswidener')

    runs {
        configureEach {
            preferGradleTask = true
        }
    }
}

java {
    sourceCompatibility = JavaVersion.VERSION_21
    targetCompatibility = JavaVersion.VERSION_21
    withSourcesJar()
    withJavadocJar()
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
    options.release = 21
}

tasks.withType(ProcessResources).configureEach {
    inputs.property 'version', project.version
    inputs.property 'minecraft_version', minecraft_version

    filesMatching('fabric.mod.json') {
        expand([
            'version': project.version,
            'minecraft_version': minecraft_version
        ])
    }
}

tasks.named('jar', Jar) {
    from('LICENSE') {
        rename { "${it}_${base.archivesName.get()}" }
    }
}

tasks.named('test', Test) {
    useJUnitPlatform()
}

spotless {
    java {
        target 'src/**/*.java'
        removeUnusedImports()
        leadingSpacesToTabs()
        trimTrailingWhitespace()
        endWithNewline()
        lineEndings = com.diffplug.spotless.LineEnding.UNIX
    }

    groovyGradle {
        target 'src/**/*.gradle', '*.gradle', 'gradle/*.gradle'
    }
}

checkstyle {
    toolVersion = checkstyle_version
    configFile = rootProject.file('checkstyle.xml')
}