[versions]
jbAnnotations = "26.1.0"

loom = "1.17-SNAPSHOT"
libninepatch = "1.2.0"
lombok = "1.18.48"
junit = "5.14.4"

[libraries]
jbAnnotations = { module = "org.jetbrains:annotations", version.ref = "jbAnnotations" }
libninepatch = { module = "io.github.juuxel:libninepatch", version.ref = "libninepatch" }
lombok = { module = "org.projectlombok:lombok", version.ref = "lombok" }

junit = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit" }
junit-launcher = { module = "org.junit.platform:junit-platform-launcher" }

[plugins]
loom = { id = "net.fabricmc.fabric-loom-remap", version.ref = "loom" }
