[versions]
jbAnnotations = "26.1.0"

loom = "1.17-SNAPSHOT"
fabric-api = "0.155.2"
fabric-loader = "0.19.3"

junit = "5.14.4"
mockk = "1.14.11"

[libraries]
jbAnnotations = { module = "org.jetbrains:annotations", version.ref = "jbAnnotations" }
fabric-api = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric-api"}
fabric-loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric-loader"}

junit = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit" }
junit-launcher = { module = "org.junit.platform:junit-platform-launcher" }
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }
mockk-agent = { module = "io.mockk:mockk-agent-jvm", version.ref = "mockk" }

[plugins]
loom = { id = "net.fabricmc.fabric-loom-remap", version.ref = "loom" }
